name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'api/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'api/**' ]

jobs:
  backend:
    name: Backend (FastAPI)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ./api/requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Type check with mypy
        run: mypy . --strict

      - name: Lint with ruff
        run: ruff check .

      - name: Format check with ruff
        run: ruff format --check .

      - name: Security check with bandit
        run: bandit -r . -f json -o bandit-report.json || true

      - name: Run tests with pytest
        run: |
          pytest tests/ -v \
            --cov=. \
            --cov-report=xml \
            --cov-report=html \
            --cov-fail-under=80 \
            --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: |
            ./api/test-results.xml
            ./api/htmlcov/
            ./api/bandit-report.json
          retention-days: 7