name: ML Package CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'ml/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'ml/**' ]
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  ml:
    name: ML Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ./ml/requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Type check with mypy
        run: mypy . --explicit-package-bases

      - name: Lint with ruff
        run: ruff check .

      - name: Format check with ruff
        run: ruff format --check .

      - name: Run tests with pytest
        run: pytest tests/ -v